AWSTemplateFormatVersion: 2010-09-09
Description: Serverless HTTP API, Website, with Auth and a DB

Parameters:
  ParamLambdaBucketUri:
    Type: String
  ParamProjectPrefix:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
  ParamProjectName:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$

Resources:
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ParamProjectPrefix}-${ParamProjectName}-api'
      Description: API Gateway
      ProtocolType: HTTP

  ApiGatewayDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties: 
      StageName: $default
      ApiId: !Ref ApiGateway
      AutoDeploy: true

  ApiGatewayDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGatewayDefaultRouteIntegration

  ApiGatewayDefaultRouteIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties: 
      ApiId: !Ref ApiGateway
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations'

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref ParamLambdaBucketUri
        S3Key: lambda.zip
      Description: Lambda function
      FunctionName:  !Sub '${ParamProjectPrefix}-${ParamProjectName}-server'
      Role: !GetAtt LambdaIAMRole.Arn
      Handler: "main"
      Runtime: "go1.x"
      MemorySize: 128
      PackageType: "Zip"
      Timeout: 10
      
  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ParamProjectPrefix}-${ParamProjectName}-server:*
          PolicyName: lambda

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ParamProjectPrefix}-${ParamProjectName}-server
      RetentionInDays: 7

  S3BucketWebAssets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ParamProjectPrefix}-${ParamProjectName}-web-assets'

  S3BucketWebAssetsPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${S3BucketWebAssets}/*'
      Bucket: !Ref S3BucketWebAssets

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: Web
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CacheBehaviors:
          - PathPattern: api/*
            TargetOriginId: Api
            Compress: false
            ViewerProtocolPolicy: 'https-only'
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
            # AWS Default CachingDisabled Policy
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        Origins:
          - Id: Web
            DomainName: !Sub '${ParamProjectPrefix}-${ParamProjectName}-web-assets.s3-${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
          - Id: Api
            DomainName: !Sub ${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'CloudFront OAI'

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ParamProjectPrefix}-${ParamProjectName}-user-pool'
      AliasAttributes: [email]
      MfaConfiguration: 'OFF'
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UsernameConfiguration:
        CaseSensitive: true
      Policies:
        PasswordPolicy: 
          MinimumLength: 7
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${ParamProjectPrefix}-${ParamProjectName}'
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      AllowedOAuthFlowsUserPoolClient: true
      GenerateSecret: true
      CallbackURLs:
        - http://localhost:3000/api/auth/login/callback
      LogoutURLs:
        - http://localhost:3000/api/auth/logout/callback
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

Outputs:
  ApiGatewayUrl:
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com
  S3BucketWebAssets:
    Value: !Sub '${ParamProjectPrefix}-${ParamProjectName}-web-assets'
  S3WebsiteUrl:
    Value: !Sub 'https://${ParamProjectPrefix}-${ParamProjectName}-web-assets.s3.${AWS::Region}.amazonaws.com'
  HostedUI:
    Value: !Sub https://${ParamProjectPrefix}-${ParamProjectName}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${CognitoUserPoolClient}&response_type=code&scope=email+openid+phone+profile&redirect_uri=http://localhost:3000
