name: Main

on:
  push:
    branches: 
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build and release
      run: |
        set -e
        TAG="$(date -u +"v%Y.%m.%d.%H%M")"

        cd template
        zip ../template.zip -r * .[^.]*
        tar -czvf ../template.tar.gz * .[^.]*
        cd ..

        gh release create "${TAG}" -n "Project template" ./template.zip ./template.tar.gz

      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
